LTO_ENABLE = yes

CONSOLE_ENABLE = no
MIDI_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
MOUSEKEY_ENABLE = yes

KEY_OVERRIDE_ENABLE = yes
OS_DETECTION_ENABLE = yes
REPEAT_KEY_ENABLE = yes

SRC += overrides.c
